[package]
name = "midas-spider"
version = "0.1.0"
edition = "2021"

[dependencies]
midas-core = { path = "../midas-core" }
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
tokio = { version = "1.26", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
