[package]
name = "midas-http"
version = "0.1.0"
edition = "2021"

[dependencies]
midas-core = { path = "../midas-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.26", features = ["full"] }
axum = { version = "0.6", features = ["http2"] }
tower-http = { version = "0.4", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
